### ISSUE TITLE
Wownero Release Naming Convention

### ISSUE THREAD

**Issue by ghost** [wownero/meta#1]
How should Wownero new releases be named?

This issue is inspired by: https://github.com/monero-project/meta/blob/master/NAMING.md

**Comment by mardarfar** [comment]
Carlos Matos

**Comment by Cactii1** [comment]
Dog breeds. Labrawow Retriever, Rottwow, Doberwow, Bullwow, Chiwowow, Daschwow, Chwow Chwow, Wowshire Terrier...

**Comment by bomb-on** [comment]
Crypto-memes or meme names in general?

e.g.
- carlos matos
- lambo
- ugandan knuckles
- dolan
- pepe
- dat boi
- lenny
- ermahgerd
- overly attached girlfriend
- wat
...

At one moment I even considered putting doge on that list too ^^

**Comment by ghost** [comment]
@bomb-on I was thinking the same. In keeping with the "Awesome Akita" theme, we can have `adjective + meme` naming convention.

**Comment by bomb-on** [comment]
"New Wownero version Financially Independently Carlos Matos is out! Now with 0% scam mmm nonono!"

Hmm... I like it, yes! :)

**Comment by jwinterm** [comment]
What's a meme that starts with 'B'? I was thinking more like @Cactii1 and planning on "Bullish Bulldog" or something, but maybe memes is better fit and could do "Bullish B Button Emoji 🅱" or something...

**Comment by ghost** [comment]
@jwinterm how about "Bullish [Boo](http://knowyourmeme.com/memes/boo-the-cutest-dog-in-the-world)"

**Comment by mardarfar** [comment]
Bogdanoffs Aliens

**Comment by matthewincognito** [comment]
Crusty Carlos.

Because we're too cool to go in alphabetical order.

**Comment by ghost** [comment]
- Benevolent Bed Intruder
- Bellicose Ken Bone
- Bossy Boxxy
- Busty Brazzers
- Brash Salt Bae
- Bouncy B Button Emoji
- Banal Rebecca Black
- Bawdy Dat Boi
- Buoyant Ice Bucket
