### ISSUE TITLE
Naming v9 Hard Fork

### ISSUE THREAD

**Issue by ghost** [wownero/meta#10]
We will probably hard fork around the same time as Monero in September/October. 

What should the name of the next fork be? 

Read Wownero’s Naming Convention [here](https://github.com/wownero/meta/blob/master/naming.md).

**Comment by ghost** [comment]
* Crusty Carlos

**Comment by ghost** [comment]
* Cheeky Cheeki

**Comment by ghost** [comment]
* Classy Cinnamon

**Comment by ghost** [comment]
* Crackerjack Coolface

**Comment by krtschmr** [comment]
Swagging Up

**Comment by krtschmr** [comment]
Boaty Mc Matosface

**Comment by jwinterm** [comment]
Catatonic C'mon do something
![image](https://user-images.githubusercontent.com/5955987/42413696-6d0c38f8-81da-11e8-862c-69b58d0702ca.png)

**Comment by dginovker** [comment]
Classy Cinnamon Classic

**Comment by bomb-on** [comment]
Carlos Connect

**Comment by Cactii1** [comment]
Charlie Bit Me Cheezus

**Comment by landergate** [comment]
Stinky Cake

**Comment by Gingeropolous** [comment]
Cool Cage

**Comment by jwinterm** [comment]
Cool cage it is
