### ISSUE TITLE
V9 Ringsize

### ISSUE THREAD

**Issue by ghost** [wownero/meta#11]
What should the ringsize for the next hard fork be?

Monero is [considering](https://github.com/monero-project/monero/issues/4229) doing static ringsize 11 and switching to a [per byte fee](https://github.com/monero-project/monero/commit/6700eb0cddef083c02a0e9488be8e332811e9337). See https://docs.google.com/document/d/1Y3IsjH7ywJOvFeZd1qT1fRfz2lw8APp8ptcyDXzYrxk/edit from ArticMine.

**Comment by SamsungGalaxyPlayer** [comment]
There is no practical difference between ringsize 10 and 11:

![capture2](https://user-images.githubusercontent.com/12520755/43790229-9a13ee16-9a37-11e8-87f1-ee1f27547f7d.PNG)

I am not aware of any specific improvements that a larger ringsize would provide. Of course bigger is strictly better, but ideally any recommendations would be grounded in specific threat-models.

[Surae Noether speaking about potential ringsizes for Monero](https://www.youtube.com/watch?v=CxXtvMTDEuY&feature=youtu.be&t=24m40s):

> We might be able to get up to ringsizes 16 or 17 or something like that...

[Also](https://www.youtube.com/watch?v=CxXtvMTDEuY&feature=youtu.be&t=30m18s):

> I don't know... there's also an argument to be made based on some of these formulas that I'm looking at that it's possible that I can look at the point at which the gain is negligible and then maybe I can be like 'once we're past 22 we can just call it quits.' And if we can get up to 22, that's so close to 7 right now. For triple our current verification time, we can just call it quits for ringsize forever? Like really? I mean that's tempting to me. But if I said that out loud smooth (a Monero Core Team member) would start yelling at me about costs to blockchain. But Aeon coin can do what they want and we can do what we want.

I unfortunately do not have access to the formulas he is referring to.

In any case, I strongly recommend a fixed ringsize for nearly any size >2.

**Comment by jwinterm** [comment]
22 then?

**Comment by ghost** [comment]
22

**Comment by ghost** [comment]
so much privacy

**Comment by ghost** [comment]
The [masses have spoken](https://twitter.com/W0wn3r0/status/1029958155835330561)... 22 it is.
