### ISSUE TITLE
Logo change discussion -- why no more 🐕

### ISSUE THREAD

**Issue by abhishek1104** [wownero/meta#13]
Let's discuss the logo (official one).

W -- Inverted M (Monero) already used by exchanges..

WoWnero = WoW (Very Impressive) + Monero (Currency).

I will say let's have some fancy W as official WoWnero logo....

Since Monero is a synonym of Currency so it gives reasonable denial that it's not just a scam fork of Monero utilising its name irrespective of launched fairly.

WoWnero has some features with distinguish it even from Monero, irrespective of lightweight focus by the core Dev's (ie it's a crypto for fun only like doge).It has the potential ,as all cryptos are still in experimental stage.

Anyways I will vote for W  -- as logo (Should look fancy).

Or if we can afford rebranding then

WoWCash Coin would be my view keeping logo as W (or inverted M).

Let's as a community have this discussion.As logo is much more than a simple symbol!

**Comment by ghost** [comment]
Issue is stale. If anyone is interested in bring it up again, comment to reopen.
