### ISSUE TITLE
Naming v10 Hard Fork

### ISSUE THREAD

**Issue by ghost** [wownero/meta#14]
What should the name of the next fork be?

Read Wownero’s Naming Convention [here](https://github.com/wownero/meta/blob/master/naming.md).

**Comment by ghost** [comment]
Dope Dab

**Comment by ghost** [comment]
Dingleberry Dreams

**Comment by ghost** [comment]
Dangerous Dragons

**Comment by ghost** [comment]
Diabetic Dwarf

**Comment by ghost** [comment]
Dimpled Dildos

**Comment by ghost** [comment]
Double Diarrhea

**Comment by ghost** [comment]
Dirty Dicks

**Comment by mardarfar** [comment]
Ding Dong

**Comment by ghost** [comment]
Dubious Dodson

**Comment by mardarfar** [comment]
Dominus Dime

**Comment by ghost** [comment]
Dank Doge

**Comment by itssteven** [comment]
dog dick(s)

**Comment by ghost** [comment]
Dwindling Dumbledore

**Comment by ghost** [comment]
Dubious Dilemma

**Comment by ghost** [comment]
Delicious Diaper

**Comment by wowviceroy** [comment]
Dirty Douche

**Comment by wowviceroy** [comment]
Dank Dildo

**Comment by wowviceroy** [comment]
Dubstep Dinosaur

**Comment by wowviceroy** [comment]
Dapper Degenerate
