### ISSUE TITLE
Raising ringsize Wownero v0.5

### ISSUE THREAD

**Issue by ghost** [wownero/meta#19]
double it... 44

**Comment by ghost** [comment]
44 is a [happy number], and 43 is a [lucky number].

Both look good to me.

[happy number]: https://en.wikipedia.org/wiki/Happy_number
[lucky number]: https://en.wikipedia.org/wiki/Lucky_number

**Comment by jwinterm** [comment]
42 is the the answer to what is the meaning of life, the universe, and
everything though...

**Comment by ghost** [comment]
In testnet, the size of a transaction with ringsize 44 is around [6.8066 kB](http://explorer.wowne.ro:8082/tx/a58dc67b9fcc172b46749c53403f888aea528f3adfdc62de8fbb148a88a3014a) and the fee 0.02091 (with fee per byte). The current transaction size with ringsize 22 is around [4.6504 kB](http://explorer.wowne.ro/tx/af25b862ef64fa02f594b5bbc8c689b97cb13b1b113d756161c4ada4d3108c28) and fee 0.0328506.

**Comment by ghost** [comment]
@SamsungGalaxyPlayer thoughts?

**Comment by SamsungGalaxyPlayer** [comment]
Honestly there's little research to support that 44 provides better protection than 22 except that it's a higher number. We haven't gotten to flex our muscles with such large ringsizes yet haha.

At such large ringsizes with bulletproofs, transaction sizes are not a _huge_ concern (but they are a slight one). Instead, Wownero should compare the verification times for transactions of different numbers of inputs. Eg (can you fill in this chart?):

Verification times

| Ringsize | 1 input | 2 inputs | 3 inputs | 5 inputs | 10 inputs |
|---|---|---|---|---|---|
| 22 |---|---|---|---|---|
| 30 |---|---|---|---|---|
| 35 |---|---|---|---|---|
| 40 |---|---|---|---|---|
| 45 |---|---|---|---|---|
| 50 |---|---|---|---|---|

**Comment by ghost** [comment]
Second, thought, there is really no compelling reason to increase ring size other than the assumption that "bigger must be better". This issue could be reopen again if anyone wants to push for a bigger ring size.
