### ISSUE TITLE
[POLL] Which operating system do you use the most?

### ISSUE THREAD

**Issue by ghost** [wownero/meta#20]
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Debian)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Debian/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Arch%20Linux)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Arch%20Linux/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Manjaro)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Manjaro/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Windows%2010)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Windows%2010/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Mac%20OS%20X)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Mac%20OS%20X/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Ubuntu)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Ubuntu/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Lubuntu)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Lubuntu/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Kubuntu)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Kubuntu/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/OpenSUSE)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/OpenSUSE/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Linux%20Mint)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Linux%20Mint/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Fedora)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Fedora/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/OpenBSD)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/OpenBSD/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/FreeBSD)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/FreeBSD/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/CentOS)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/CentOS/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/elementary%20OS)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/elementary%20OS/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Qubes%20OS)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Qubes%20OS/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Tails)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Tails/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Kali)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Kali/vote)
[![](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Whonix)](https://api.gh-polls.com/poll/01D0J4A605SGPX6GWVVS0KAXBM/Whonix/vote)

**Comment by ghost** [comment]
If other OS, post comment

**Comment by bomb-on** [comment]
TempleOS? 💻

**Comment by astraleureka-zz** [comment]
Alpine Linux, shipping a Wownero package in my custom repository.

**Comment by ghost** [comment]
ChromeOS +1, NixOS +1

**Comment by ghost** [comment]
Thanks to everyone who answered.
