### ISSUE TITLE
v0.6 Testnet

### ISSUE THREAD

**Issue by ghost** [wownero/meta#23]
**Testnet Repos**

Testnet 1 - RandomX
* git clone https://github.com/wowario/wownero testnet1
* cd testnet1
* git checkout testnet1 && make

Testnet 2 - RandomWOW
* git clone https://github.com/wowario/wownero testnet
* cd testnet
* git checkout testnet && make
* [Testnet RandomWOW Explorer](http://explorer.wowne.ro:8082)

Run 
`./wownerod --testnet`

Start mining with 2 threads
```
start_mining 9w9hqLiD6CtJ9kQZ4H5UY1PFVtwKJjhwGabkeXvKpmK2146zN5uuVjL7Skdw3bt3Qi8hr4HkXALgwWC4WpRG7pKXKCVhHpA 2
```
See hash rate
`show_hr`

**Comment by itssteven** [comment]
Lenovo X220 (i5-2520M)

With 2 threads:

Testnet 1 - default RandomX: 380h/s
Testnet 2 - RandomWOW: 500h/s

**Comment by ghost** [comment]
Intel i5-8250U

With 2 threads:

Testnet 1 - RandomX: 661 H/s
Testnet 2 - RandomWOW: 810 H/s

**Comment by sanderfoobar** [comment]
AMD Ryzen Threadripper 2920X

With 2 threads:

Testnet 1 - RandomX: 920 H/s
Testnet 2 - RandomWOW: 1020 H/s

**Comment by Bathmat** [comment]
Ryzen 1700 - 8 threads:

Current cn/wow: 550 h/s
Testnet 1: 1950 h/s
Testnet 2: 3440 h/s

**Comment by ghost** [comment]
A quick test on testnet2: block reward is wrong and sending tx gave errors: 

```
Error: transaction <a767...> was rejected by daemon
Error: Reason: invalid output
```

**Comment by bomb-on** [comment]
**Intel i3-7100 - 2 threads**

Current cn/wow: 60 h/s
Testnet 1 - RandomX: 630 H/s
Testnet 2 - RandomWOW: 780 H/s

**Intel i5-4690K - 2 threads**

Current cn/wow: 210 h/s
Testnet 1 - RandomX: 950 H/s
Testnet 2 - RandomWOW: 1130 H/s

**Intel i5-5257U - 2 threads (macOS)**

Current cn/wow: 40 h/s
Testnet 1 - RandomX: 400 H/s
Testnet 2 - RandomWOW: 550 H/s

**Comment by ghost** [comment]
initial testing complete
