### ISSUE TITLE
fuwa will probably fork anyway

### ISSUE THREAD

**Issue by ghost** [wownero/meta#29]
I think I'll fork with or without you. I won't be interested to work on a slow syncing chain, and it's more important for me to not regret doing something than to worry about failing.

I think miners and users should have a choice, and the market should decide which to follow. I understand that a chain fork isn't ideal, but there's plenty of monero classic already, and they don't seem to matter after a while.

I'm willing to transfer wownerujo, cyberwow and wowllet to another android developer, and if there's no transfer arranged, these will be taken down from the play store since I won't be maintaining them.

If wownero decide to stay with CPU mining, I'll just comment out the hardfork date and that's pretty much about it.

**Comment by tevador** [comment]
> slow syncing chain

If that's your reason for forking, then why not fork to [Equi-X](https://github.com/tevador/equix), which offers both CPU mining and fast verification?

**Comment by ghost** [comment]
I'm not anti ASIC, if Equi-X becomes a hashing standard like SHA-3, supported by endless funding from the industry and will eventually be replaced by another standard like SHA-4, if broken, all without me doing anything, sure.

Otherwise, hmm.

**Comment by ghost** [comment]
wouldn't it be better to launch a new chain to avoid a MoneroV linking key images type situation? also, there would be the added benefit of having a fast syncing chain from block 0.

**Comment by ghost** [comment]
@wowario yes, but can you prevent a chain fork if wownero goes SHA-3? Will there not be a wownero classic when so many want to stay with CPU mining? now or any other time in the future?

**Comment by tevador** [comment]
> Equi-X becomes a hashing standard like SHA-3

I think you should read [this](https://www.reddit.com/r/Monero/comments/8bshrx/what_we_need_to_know_about_proof_of_work_pow/) to better understand the difference between a hashing function and a proof-of-work function.

Yes, SHA-3 is a certified and peer-reviewed hashing function. It was designed to transform an arbitrary size document into a fixed-length digest. However, it is not certified to be used as a proof of work function. Using a hashing function as PoW is nothing more than a heuristic.

'Certified' uses of hash functions are for example block hashes, transaction hashes or Merkle trees. Nobody is suggesting to use Equi-X or RandomX for that.

**Comment by ghost** [comment]
@tevador Thanks. As I said, I want the market to decide. I'm not saying SHA-3 is better choice for everyone.

BTW, if @jwinterm wants me to not do a chain split. I'll respect that, since he's the creator. I'll ignore opinions from investors and developers, sorry.

**Comment by ghost** [comment]
> prevent a chain fork if wownero goes SHA-3

Really depends on coordination with exchanges, pools, and how well the "core" team acts in unison. We have forked away from NiceHash/ASIC'd Cryptonight variants to remain CPU-mineable. Brute hashing power alone is not sufficient for a successful fork imo, there is a degree of social finesse. Granted Wownero was smaller and only a handful people were interested in it in the past.

As interest in Wownero grows, there should be a formal method of resolving significant issues like this. We could look at [Monero](https://web.getmonero.org/2016/02/10/monero-missive-2015-year-in-review.html) and [CentOS](https://www.centos.org/about/governance/appendix-glossary/) governance approach as an example.

**Comment by Gingeropolous** [comment]
>  As I said, I want the market to decide. 

Because that works great, especially all of these well functioning markets. 

I'm sorry I'm sorry I won't pepper this conversation with my cynicism anymore....

**Comment by ghost** [comment]
@wowario It's all very convincing, until I recall what the last release was named. It's cool though. And that informal process got us here.

Maybe I won't be interested to even do a chain split after eight months, who knows.

**Comment by jwinterm** [comment]
@fuwa0529 I am generally in agreement with you about changing the proof-of-work algorithm, however, it also seems like most people don't want to change it at this point. I am working with someone trying to get an open source implementation of sha3 hashing algorithm that runs on low-end fpgas - maybe this would help garner some more support.

I don't really care if you do decide to fork off, just please keep us in the loop if you don't mind. I guess I will try and get a developer account set up with google play so that I can take over the apps in the next few weeks. I'd definitely like to keep them up, they are really a great contribution!

**Comment by sumogr** [comment]
My two cents coming from a place that experienced huge drama and it is all our fault cause we allowed it to happen. wownero and all open projects belong to no one ,they are a common effort of people that prefer to spend their time in doing something creative and maybe useful.  "Leaders" and "founders" belong to ICOs and financial crypto ponzi schemes or in extreme cases "cult-like" toxic projects like our friend's the "legendary security expert, cryptographer, omnipotent developer" aka "autistic turd" project. Disagreements are healthy, but @fuwa0529  you stand the chance of being labelled as someone who tried to make his own coin to capitalise on the value wownero suddenly acquired. The timing is very bad to express your concerns in this way. My humble opinion spawn a genesis block and create a native fork, this will also give you more coding freedom to do what you want, delete obsolete code from bitmonero or wownero, lighten up the chain and so on. Sorry for intervening i fell upon this and felt familiar

**Comment by ghost** [comment]
@sumogr OK, I think you convinced me. I won't fork. I don't really know how to maintain a fork anyway.
