### ISSUE TITLE
Migrate to self-hosted git instance

### ISSUE THREAD

**Issue by ghost** [wownero/meta#30]
I've stated to migrate Wownero repos to https://git.wownero.com/wownero

Should we move development there?

- +1 (Yea)
- -1 (Nay)
- 0 (Shrug)

**Comment by jwinterm** [comment]
How easy is it to mirror stuff back to regular github? Also if wow grows in popularity does bandwidth of server become an issue?

**Comment by sanderfoobar** [comment]
bandwidth on the git server is currently an unmetered line rated at 250mbit. This should be sufficient, and in the future I can upgrade it to 500mbit if neccesary.

**Comment by ghost** [comment]
It is possible to [mirror repositories to Github](https://help.github.com/en/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github#open-source-projects-with-mirrors-on-github).

**Comment by jwinterm** [comment]
OK I am +1

**Comment by sanderfoobar** [comment]
Git server has been strategically hosted in London so both US east coast and Europe should have good response times. Seemed like a good compromise judging from where our contributors are from (Europe/US).

**Comment by ghost** [comment]
migrated to https://git.wownero.com/wownero/meta
