### ISSUE TITLE
Migrate subreddit to self-hosted forum

### ISSUE THREAD

**Issue by ghost** [wownero/meta#31]
We could make the Wownero's subreddit private and redirect people to https://forum.wownero.com. 

[Z-cash](https://www.reddit.com/r/Zcash/) follows this approach.

+1 (Yea)
-1 (Nay)
0 (Shrug)

**Comment by jwinterm** [comment]
Not sure we need to shutdown the subreddit, maybe just sticky link to forum? Shutting down the subreddit just leads to people opening an alternate subreddit anyway if there's any interest at all. I understand the desire not to dilute social channels to the point that they appear inactive, but I don't think it requires trying to force people off of a particular platform.

**Comment by ghost** [comment]
migrated to https://git.wownero.com/wownero/meta
