### ISSUE TITLE
Switch over to GitLab

### ISSUE THREAD

**Issue by ghost** [wownero/meta#5]
In light of the Microsoft's acquisition of GitHub, should we jump ship to GitLab?

**Comment by jwinterm** [comment]
I don't feel too strongly either way. I guess as a start we can at least duplicate repo there?

**Comment by sanderfoobar** [comment]
gitlab is actually lots of bloat to be hosting yourself. Consider running https://github.com/go-gitea/gitea

**Comment by ghost** [comment]
Mirror repository added to Gitlab: https://gitlab.com/wownero/wownero
