### ISSUE TITLE
Moar wowski art!

### ISSUE THREAD

**Issue by bomb-on** [wownero/meta#7]
Related to https://github.com/wownero/wownero/commit/bcf485d9a7ffe7b9cd1696e6f3096f1a620eeaae commit... Can we add more ascii art, like 10-20 pieces from which one would be randomly chosen on each daemon startup?

That would be just great!

**Comment by pazos** [comment]
@bomb-on: please keep compatibility in daemon messages with monerod. It is ok to choose between random strings at startup, but the log should has the same format as monerod.

**Comment by ghost** [comment]
migrated to https://git.wownero.com/wownero/meta
