### ISSUE TITLE
Testnet Faucet Website

### ISSUE THREAD

**Issue by ghost** [wownero/meta#9]
Create a testnet faucet site so people could withdraw and deposit testnet WOW similar to https://dis.gratis

**Comment by bomb-on** [comment]
I might take a look at this, but not sooner than a week or so from now :)

Just two quick questions:
 - do we want ability to "withdraw" manually entered amount of ⍵?
 - do we want to host this on testnet machine we have now?

**Comment by ghost** [comment]
Guess limiting manual withdraws up to a certain amount per transaction would be okay. I have a server available that we could put the faucet site on.

**Comment by pazos** [comment]
a mainnet faucet would be great too :p

**Comment by ghost** [comment]
We could just fork this over to Wownero: https://github.com/krruzic/TurtleFaucet

**Comment by ghost** [comment]
Not really needed. Testnet is for wussies.
